# Generated by Django 5.2.11 on 2026-06-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='banner_bann_image_c_fb39d4_idx',
            old_name='banner_bann_image_c_idx',
        ),
        migrations.RenameIndex(
            model_name='banner',
            new_name='banner_bann_is_acti_3d35ad_idx',
            old_name='banner_bann_is_acti_idx',
        ),
    ]
